site_name: UL Book
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime


copyright: |
  &copy; 2024 <a href="https://github.com/chendamere"  target="_blank" rel="noopener">Hankai Chen</a>

nav:
  - Home: index.md
  - About: about.md
